services:
  - type: web
    name: Agora Server
    env: python
    repo: https://github.com/tadaspetra/agora-server.git
    rootDir: .
    buildCommand: pip install flask
    startCommand: python3 -m flask run
    plan: free
    envVars:
      - key: APP_ID
        sync: false
      - key: ACCESS_KEY
        sync: false
      - key: BUCKET_NAME
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: CUSTOMER_KEY
        sync: false
      - key: CUSTOMER_SECRET
        sync: false
